# This workflow runs the tests, builds the image and starts the deploy-script for olahd-backend on the devserver

name: olahd-ci-to-develop
on:
  push:
    branches:
      - 'develop'
    tags:
      - !v*.*.*
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: stop test-mongodb if running
      run: docker stop mongodb-test || true && docker rm mongodb-test || true
    - name: start test-mongodb
      run: docker run -v mongodb:/data-test/db -p 27018:27017 --name mongodb-test -e MONGO_INITDB_ROOT_USERNAME=test -e MONGO_INITDB_ROOT_PASSWORD=testtest -d mongo:4.0.10
    - name: run tests
      run: mvn test

  # builds docker image to test if dockerfiles are working
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image with version
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    

  # deploy on the devserver via script located on devserver
  deploy-develop:
    name: Deploy to develop
    environment:
      name: Develop
    if: github.event.ref == 'refs/heads/develop'
    #if: github.ref == 'refs/heads/main'
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - name: copy key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_DEV_KEY" > ~/.ssh/key
          chmod 600 ~/.ssh/key
        env:
          SSH_DEV_KEY: ${{ secrets.OLAHD_SSH_DEV_KEY }}
      - name: deploy to server
        run: ssh $SSH_DEV_USER@$SSH_DEV_HOST -o StrictHostKeyChecking=no -i ~/.ssh/key /home/$SSH_DEV_USER/start-olahd-docker.sh
        env:
          SSH_DEV_USER: ${{ secrets.OLAHD_SSH_DEV_USER }}
          SSH_DEV_HOST: ${{ secrets.OLAHD_SSH_DEV_HOST }}
    